### ISSUE TITLE
Harish Case Study with Edureka web page

### ISSUE THREAD

**Issue by Harish-Ramanathan** [tabhresh/Edureka_29thApril#1]
Hi Abresh,

Kindly check the code which I added here, I need system to click on search button and result should be displayed. I tried with web element which is unique but code not worked.

Please check and help me out what is the reason for it and provide me a solution. Thank you

package edurekaSeleniumPackage;
import java.util.concurrent.TimeUnit;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

public class CaseStudy2 {

	public static void main(String[] args) throws InterruptedException {

		// Launch Browser
		System.setProperty("webdriver.chrome.driver", "H:/Edureka Installation Guide for Selenium/chromedriver.exe/");
		WebDriver driver = new ChromeDriver();
		driver.get("https://www.edureka.co/");

		// Page Load time of 20 Seconds
		driver.manage().timeouts().pageLoadTimeout(20, TimeUnit.SECONDS);

		// Maximise the window
		driver.manage().window().maximize();

		// Implicit Wait time of 20 Seconds for all actions
		driver.manage().timeouts().implicitlyWait(20, TimeUnit.SECONDS);

		// Enter the data to be searched
		driver.findElement(By.xpath("//input[@class='search_inp collapse giTrackElementHeader']")).sendKeys("Selenium");

		// Perform Search on WebPage
		driver.findElement(By.xpath("//span[@class='typeahead__button']")).click();

	}

}

**Comment by AbhreshSugandhi** [comment]
Hi,

The problem was the locator which was incorrect we were taking locator of the image whereas actually there was an internal element which you can see if you expand the element and then the ID locator worked for me.

	// Enter the data to be searched
	driver.findElement(By.xpath("//input[@class='search_inp collapse giTrackElementHeader']")).sendKeys("Selenium");
	
	// Perform Search on WebPage
	driver.findElement(By.xpath("//*[@id='search-button-top']")).click();


![error](https://user-images.githubusercontent.com/22336822/57622651-b64f0480-75ab-11e9-9cad-e353c722307c.jpg)
