### ISSUE TITLE
Automatinpractice

### ISSUE THREAD

**Issue by prpatel723** [tabhresh/Edureka_29thApril#2]
package module1;

import java.util.List;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;

public class Automatinpractice {

	public static void main(String[] args) throws InterruptedException{
		
		//Open Bowser
		System.setProperty("webdriver.chrome.driver", "C:\\Program Files\\Selenium\\Installation stuff\\Drivers\\chromedriver.exe");
		WebDriver driver = new ChromeDriver();
				
		//Open AUT
		driver.get("http://automationpractice.com/index.php");
		
		//Using linkText
		driver.findElement(By.linkText("Sign in")).click();
		
		//Using name
		driver.findElement(By.name("search_query")).sendKeys("top");
		
		//Using id
		driver.findElement(By.id("email")).sendKeys("Priya");
		
		//Using css
		driver.findElement(By.cssSelector("input#search_query")).sendKeys("Tops");
		
		//Using Tag name
		driver.findElement(By.tagName("input"));
		List<WebElement> list = driver.findElements(By.tagName("input"));
		System.out.println(list.size());
		
		//Using Partial link text
		driver.findElement(By.partialLinkText("your pass")).click();
		driver.navigate().back();	
		
		//Using Xpath
		driver.findElement(By.xpath("//img[@id=\"header_logo\"]")).click();

	}

}
not getting expected result here

**Comment by AbhreshSugandhi** [comment]
First of all, you have taken the wrong locators.
in comments, you have not what are you trying to do! 
No clarity what are you expecting from this script.

Practice more with normal stuff and focus more on the practice along with practice watch the recordings otherwise you will keep doing small small basic level mistakes with will lead to losing your confidence.

**Comment by prpatel723** [comment]
Which locators are wrong here?  The one with the tag name is there which I tried after watching video only and I tried to find out the error also but not able to get the error. I checked so many times but I feel similar to our script only. So Please help me to find out that error.

And also the one with the logo img I tied it was working I kept other section in comments and run only that portion but I want to run all together.

**Comment by AbhreshSugandhi** [comment]
//Using css - this locator is wrong
	driver.findElement(By.cssSelector("**input#search_query**")).sendKeys("Tops");
	
	//Using Tag name - what is the use of this line of code as it dosent result in to any action!
	**driver.findElement(By.tagName("input"));**
	List<WebElement> list = driver.findElements(By.tagName("input"));
	System.out.println(list.size());

**Comment by prpatel723** [comment]
that locator was working for me to enter tops in the search box. And yes next line is for practice only to get the no of input tags. As you showed.

package module1;

import java.util.List;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;

public class Automatinpractice {

	public static void main(String[] args) throws InterruptedException{
		
		//Open Bowser
		System.setProperty("webdriver.chrome.driver", "C:\\Program Files\\Selenium\\Installation stuff\\Drivers\\chromedriver.exe");
		WebDriver driver = new ChromeDriver();
				
		//Open AUT
		driver.get("http://automationpractice.com/index.php");
		
		//Using linkText clicking sign in button
		driver.findElement(By.linkText("Sign in")).click();
		
		//Using name trying to enter top in search box
		//driver.findElement(By.name("search_query")).sendKeys("top");
		
		//Using id entering value in email box
		driver.findElement(By.id("email")).sendKeys("Priya");
		
		//Using xpath to enter password
		driver.findElement(By.xpath("//*[@id=\"passwd\"]")).sendKeys("patel");
		
		//Using css to enter top in search box
		driver.findElement(By.cssSelector("input#search_query_top")).sendKeys("Tops");
		
		//Using Tag name to check the number of input tags in code
		driver.findElement(By.tagName("input"));
		List<WebElement> list = driver.findElements(By.tagName("input"));
		System.out.println(list.size());
		
		//Using Partial link text to click on Forgot your password and then navigate back to previous page
		driver.findElement(By.partialLinkText("your pass")).click();
		driver.navigate().back();	
		
		//Using Xpath trying to click on logo to get back to home page
		driver.findElement(By.xpath("//*[@id=\"header_logo\"]/a/img]")).click();
	}
}
