### ISSUE TITLE
Facebook

### ISSUE THREAD

**Issue by prpatel723** [tabhresh/Edureka_29thApril#4]
package module1;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;

public class Facebook {

	public static void main(String[] args) {
		
		//Open Bowser
		System.setProperty("webdriver.chrome.driver", "C:\\Program Files\\Selenium\\Installation stuff\\Drivers\\chromedriver.exe");
		WebDriver driver = new ChromeDriver();
		
		//Open AUT
		driver.get("https://www.facebook.com/");
		
		
		/*Using id
		driver.findElement(By.id("u_0_c")).sendKeys("Priya");
		driver.findElement(By.id("u_0_e")).sendKeys("Patel");
		driver.findElement(By.id("u_0_h")).sendKeys("7327072320");
		
		//Using Name
		driver.findElement(By.name("firstname"));
		
		//Using Class Name
		driver.findElement(By.className("inputtext")).sendKeys("Priya");
		driver.findElement(By.className("inputtext")).sendKeys("Patel");
		
		
		//Using Linktext
		driver.findElement(By.linkText("Forgot account?")).click();
		
		//To navigate back to home page
		driver.navigate().back();
		
		
		//Using Partial Link Text
		driver.findElement(By.partialLinkText("do I")).click();
		*/
		
		//Using CSS
		//driver.findElement(By.cssSelector("input#text-input-what")).sendKeys("BA");
		
		//WebElement te = driver.findElement(By.xpath("//*[contains(text(),'Connect with')"));
		//te.getText();
		//System.out.println(te);
		
		//driver.findElement(By.xpath("//*[@id='month']//following::select/option[12]")).click();
		//driver.findElement(By.xpath("//*[@id='month' and @name='birthday_month']//following::select/option[12]")).click();
		//driver.findElement(By.xpath("//*[@id='year' and @name='birthday_year']//following::select/option[33]")).click();
		//driver.findElement(By.xpath("//*[@id='day' and @name='birthday_day']//following::select/option[2]")).click();
		
		driver.findElement(By.xpath("//*[@id='month' and @name='birthday_month']//following::select[1]/option[3]")).click();
		//driver.findElement(By.xpath("")).click();
		driver.findElement(By.xpath("//*[@id='day' and @name='birthday_day']//following::select[1]/option[33]")).click();
	}
}

In this code I am facing problem with webelement and in the last five lines trying to get the year,month and date but not getting expected results

**Comment by AbhreshSugandhi** [comment]
package Issues;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;

public class PriyaFacebook {

public static void main(String[] args) {
	
	//Open Bowser
	System.setProperty("webdriver.chrome.driver", "F:\\Training\\Installation_stuff\\ExeFiles\\chromedriver.exe");
	WebDriver driver = new ChromeDriver();
	
	//Open AUT
	driver.get("https://www.facebook.com/");
	
	
	/*Using id
	driver.findElement(By.id("u_0_c")).sendKeys("Priya");
	driver.findElement(By.id("u_0_e")).sendKeys("Patel");
	driver.findElement(By.id("u_0_h")).sendKeys("7327072320");
	
	//Using Name
	driver.findElement(By.name("firstname"));
	
	//Using Class Name
	driver.findElement(By.className("inputtext")).sendKeys("Priya");
	driver.findElement(By.className("inputtext")).sendKeys("Patel");
	
	
	//Using Linktext
	driver.findElement(By.linkText("Forgot account?")).click();
	
	//To navigate back to home page
	driver.navigate().back();
	
	
	//Using Partial Link Text
	driver.findElement(By.partialLinkText("do I")).click();
	*/
	
	//Using CSS
	//driver.findElement(By.cssSelector("input#text-input-what")).sendKeys("BA");
	
	//WebElement te = driver.findElement(By.xpath("//*[contains(text(),'Connect with')"));
	//te.getText();
	//System.out.println(te);
	
	//driver.findElement(By.xpath("//*[@id='month']//following::select/option[12]")).click(); // this is working
	//driver.findElement(By.xpath("//*[@id='month' and @name='birthday_month']//following::select/option[12]")).click();
	//driver.findElement(By.xpath("//*[@id='year' and @name='birthday_year']//following::select/option[33]")).click();//INCORRECT OPTION NO [33]
	//driver.findElement(By.xpath("//*[@id='day' and @name='birthday_day']//following::select/option[2]")).click();// HERE CORRECT XPATH SHOULD BE //*[@id='day' and @name='birthday_day']//following::select[1]/option[2]
	
	driver.findElement(By.xpath("//*[@id='month' and @name='birthday_month']//following::select[1]/option[3]")).click();
	//driver.findElement(By.xpath("")).click();
	driver.findElement(By.xpath("//*[@id='day' and @name='birthday_day']//following::select[1]/option[33]")).click();
}
}

![error](https://user-images.githubusercontent.com/22336822/57688945-37fe6b00-765c-11e9-90e7-1d95f3fcfa66.gif)

**Comment by prpatel723** [comment]
For year why 33 is wrong selection if I want to select 1988 then.

package module1;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;

public class Facebook {

	public static void main(String[] args) {
		
		//Open Bowser
		System.setProperty("webdriver.chrome.driver", "C:\\Program Files\\Selenium\\Installation stuff\\Drivers\\chromedriver.exe");
		WebDriver driver = new ChromeDriver();
		
		//Open AUT
		driver.get("https://www.facebook.com/");
		
		/*Using id
		driver.findElement(By.id("u_0_c")).sendKeys("Priya");
		driver.findElement(By.id("u_0_e")).sendKeys("Patel");
		driver.findElement(By.id("u_0_h")).sendKeys("7327072320");
		
		//Using Name
		driver.findElement(By.name("firstname"));
		
		//Using Class Name
		driver.findElement(By.className("inputtext")).sendKeys("Priya");
		driver.findElement(By.className("inputtext")).sendKeys("Patel");
		
		
		//Using Linktext
		driver.findElement(By.linkText("Forgot account?")).click();
		
		//To navigate back to home page
		driver.navigate().back();
		
		
		//Using Partial Link Text
		driver.findElement(By.partialLinkText("do I")).click();
		*/
		
		//Using CSS
		//driver.findElement(By.cssSelector("input#text-input-what")).sendKeys("BA");
		
		//WebElement te = driver.findElement(By.xpath("//*[contains(text(),'Connect with')"));
		//te.getText();
		//System.out.println(te);
		
		//driver.findElement(By.xpath("//*[@id='month']//following::select/option[12]")).click();
		//driver.findElement(By.xpath("//*[@id='month' and @name='birthday_month']//following::select/option[12]")).click();
		//driver.findElement(By.xpath("//*[@id='year' and @name='birthday_year']//following::select/option[33]")).click();
		//driver.findElement(By.xpath("//*[@id='day' and @name='birthday_day']//following::select[1]/option[2]")).click();
		
		driver.findElement(By.xpath("//*[@id='month' and @name='birthday_month']//following::select/option[3]")).click();
		driver.findElement(By.xpath("//*[@id='day' and @name='birthday_day']//following::select[1]/option[3]")).click();
		driver.findElement(By.xpath("//*[@id='month' and @name='birthday_year']//following::select/option[33]")).click();
	}
}

In this code I am not getting the error description also but just getting one dialog box saying 
Please try to run from your end and let me know the results I am trying to get march 4 1988.

**Comment by AbhreshSugandhi** [comment]
I feel the XPath concepts need to be re-revised because the Xpath created was not navigating to your required elements correctly, and if you focus more in my response and study the change, you could easily find a solution to your problem. I seriously feel Xpath revision is required.

**Comment by prpatel723** [comment]
public class Facebook {

	public static void main(String[] args) {
		
		//Open Bowser
		System.setProperty("webdriver.chrome.driver", "C:\\Program Files\\Selenium\\Installation stuff\\Drivers\\chromedriver.exe");
		WebDriver driver = new ChromeDriver();
		
		//Open AUT
		driver.get("https://www.facebook.com/");
		
		/* Passing values in firstname,lastname and mobile number field in home page using id
		driver.findElement(By.id("u_0_c")).sendKeys("Priya");
		driver.findElement(By.id("u_0_e")).sendKeys("Patel");
		driver.findElement(By.id("u_0_h")).sendKeys("7327072320");
		
		//Passing values in firstname using Name
		driver.findElement(By.name("firstname"));
		
		//Using Class Name
		driver.findElement(By.className("inputtext")).sendKeys("Priya");
		driver.findElement(By.className("inputtext")).sendKeys("Patel");
		
		//Click on Forgot account in home page with the help of linktext
		driver.findElement(By.linkText("Forgot account?")).click();
		
		//To navigate back to home page
		driver.navigate().back();
		
		
		//Click on 'do I' in home page with the help of Partial Link Text
		driver.findElement(By.partialLinkText("do I")).click();
		*/
		
		//Trying to find the text Connect with in home page of facebook and trying to print in console
		WebElement te = driver.findElement(By.xpath("//*[contains(text(),'Connect with')"));
		te.getText();
		System.out.println(te);
		
		//Passing values for month,date and year in home page of facebook
		driver.findElement(By.xpath("//*[@id='month' and @name='birthday_month']//following::select/option[3]")).click();
		driver.findElement(By.xpath("//*[@id='day' and @name='birthday_day']//following::select/option[3]")).click();
		driver.findElement(By.xpath("//*[@id='year']//following::select[1]/option[30]")).click();
	}
}

I tried a lot but not getting any results with the not commented codes. Please try to find out the solution I watched that x path videos so many times and even I am able to get the results with x-path for other things but not getting with this code. Please help me  because if i use id =year it shows me it as a unique one but once I started selecting other things it will go to day option.

**Comment by AbhreshSugandhi** [comment]
package Issues;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;

public class Facebook {

	public static void main(String[] args) {

		// Open Bowser
		System.setProperty("webdriver.chrome.driver", "C:\\Program Files\\Selenium\\drivers\\chromedriver_2.46.exe");
		WebDriver driver = new ChromeDriver();

		// Open AUT
		driver.get("https://www.facebook.com/");

		/*
		 * Passing values in firstname,lastname and mobile number field in home page
		 * using id driver.findElement(By.id("u_0_c")).sendKeys("Priya");
		 * driver.findElement(By.id("u_0_e")).sendKeys("Patel");
		 * driver.findElement(By.id("u_0_h")).sendKeys("7327072320");
		 * 
		 * //Passing values in firstname using Name
		 * driver.findElement(By.name("firstname"));
		 * 
		 * //Using Class Name
		 * driver.findElement(By.className("inputtext")).sendKeys("Priya");
		 * driver.findElement(By.className("inputtext")).sendKeys("Patel");
		 * 
		 * //Click on Forgot account in home page with the help of linktext
		 * driver.findElement(By.linkText("Forgot account?")).click();
		 * 
		 * //To navigate back to home page driver.navigate().back();
		 * 
		 * 
		 * //Click on 'do I' in home page with the help of Partial Link Text
		 * driver.findElement(By.partialLinkText("do I")).click();
		 */

		// Trying to find the text Connect with in home page of facebook and trying to
		// print in console
		String te = driver.findElement(By.xpath("//*[contains(text(),'Connect with')")).getText();
		/*
		 * //I dont see any content having the words "Connect with" as it is. 
		 * Why dont you try working with normal ways first and then do R&D, also the missing
		 * brackets in the script is also going to impact you wrote the xpath as -
		 * "//*[contains(text(),'Connect with')" correct one is -
		 * "//*[contains(text(),'Connect with')]" the bracket closer was missing apart
		 * from that even the contents functions used was incorrect i didnt explained
		 * you can use any randum words out of the complete text I said any word or any
		 * part of it but in continuations - "connect and share with" and u used it as
		 * "connect with"
		 */
		System.out.println(te);

		// Passing values for month,date and year in home page of facebook

		driver.findElement(By.xpath("//*[@id='month' and @name='birthday_month']//following::select/option[3]")).click();// Only this is correct
		driver.findElement(By.xpath("//*[@id='day' and @name='birthday_day']//following::select/option[3]")).click(); 
		// not a unique Xpath
		driver.findElement(By.xpath("//*[@id='year']//following::select[1]/option[30]")).click(); // incorrect Xpath
	}
}
